
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: hellowhale
  namespace: default
spec:
  containers:
  - image: ealday/hellowhale:${BUILD_NUMBER}
    name: healday/hellowhale:${BUILD_NUMBER}


apiVersion: v1
kind: Service
metadata:
  name: hellowhale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale.gotouche.com.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellowhale
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: ealday/hellowhale:${BUILD_NUMBER}
        name: ealday/hellowhale:${BUILD_NUMBER}
        ports:
        - containerPort: 80