apiVersion: v1
kind: Service
metadata:
  name: hellowhale
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale.gotouche.com.
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
