apiVersion: v1
kind: Service
metadata:
  name: hellowhale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale.gotouche.com.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hellowhale

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellowhale=$IMAGE_NAME
spec:
  template:
    metadata:
      labels:
        app: hellowhale
    spec:
      containers:
      - image: hellowhale=$IMAGE_NAME
        name: hellowhale=$IMAGE_NAME
        ports:
        - containerPort: 80