apiVersion: v1
kind: Service
metadata:
  name: hellowhale
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale.gotouche.com.
spec:
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 80
  selector:
    app: nginx
