
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: hellowhale
  namespace: default
spec:
  containers:
  - image: ealday/hellowhale:latest
    name: hellowhale

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellowhale
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: hellowhale
    spec:
      containers:
      - name: hello
        image: ealday/hellowhale:latest
        ports:
        - containerPort: 8080
        
apiVersion: v1
kind: Service
metadata:
  name: hellowhale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale.gotouche.com.
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx