apiVersion: v1
kind: Service
metadata:
  name: hellowhlae
  namespace: ${KUBERNETES_NAMESPACE}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hellowhale
spec:
  ports:
  - name: hellowhale
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
