apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: hellowhale
  namespace: --namespace=${KUBERNETES_NAMESPACE}
spec:
  containers:
  - image: ealday/hellowhale:latest
    name: hellowhale
    ports:
    - containerPort: 8080
