apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: hellowhale
  namespace: default
spec:
  containers:
  - image: ${IMAGE_NAME}
    name: hellowhale
    ports:
    - containerPort: 8080
